spring.datasource.url=jdbc:sqlserver://vaishnavi-taskportal-sqlserver.database.windows.net:1433;databaseName=vaishnavi-taskdb;encrypt=true;trustServerCertificate=false
spring.datasource.username=vaishnaviadmin
spring.datasource.password=YourPasswordHere
spring.jpa.show-sql=true
