trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildReact
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
    - script: |
        cd student-management-frontend/student-management-frontend
        npm install
        npm run build
      env:
        REACT_APP_API_URL: https://vaishnavi-taskportal-api-azfgd0anh0bubmgv.centralindia-01.azurewebsites.net
    - publish: student-management-frontend/student-management-frontend/build
      artifact: frontend-build

- stage: DeployStaging
  dependsOn: Build
  environment: staging
  jobs:
  - deployment: DeployUIStaging
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: pgsn-intern-arm-svc
              appName: vaishnavi-taskportal-ui
              appType: webAppLinux
              package: $(Pipeline.Workspace)/frontend-build

- stage: DeployProduction
  dependsOn: DeployStaging
  environment: production
  jobs:
  - deployment: DeployUIProd
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: vaishnavi-taskportal-connection
              appName: vaishnavi-taskportal-ui
              appType: webAppLinux
              package: $(Pipeline.Workspace)/frontend-build
